twig:
    form_themes: ['bootstrap_5_horizontal_layout.html.twig']
    default_path: '%kernel.project_dir%/templates'
    globals:
        app_url_api: '%env(resolve:URL_API)%'

when@test:
    twig:
        strict_variables: true

